# Generated by Django 4.0.3 on 2022-03-10 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated',
        ),
        migrations.AddField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
