# Generated by Django 4.0.3 on 2022-03-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebookurl',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagramurl',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitterurl',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='websiteurl',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
