# Generated by Django 4.0.3 on 2022-03-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_profile_facebookurl_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/static/images/profile'),
        ),
    ]
