# Generated by Django 4.0.3 on 2022-03-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_profile_private_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
