# Generated by Django 4.0.3 on 2022-04-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_alter_profile_facebookurl_alter_profile_instagramurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='movie/static/images/profile/default.png', null=True, upload_to='movie/static/images/profile'),
        ),
    ]
