# Generated by Django 4.0.3 on 2022-04-07 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebookurl',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagramurl',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitterurl',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='websiteurl',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
