# Generated by Django 4.0.3 on 2022-04-27 05:12

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_alter_profile_facebookurl_alter_profile_instagramurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the movie', max_length=1000, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='request',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='request',
            name='subject',
            field=models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
